name: change-version-action
description: 'Change version for helmfile'
author: "dutchakdev"
branding:
  icon: 'arrow-right-circle'
  color: 'purple'
inputs:
  service:
    description: "Service name in helmfiles/envs/{namespace}/services"
    required: true
  service_version:
    description: "Service version"
    required: true
  namespace:
    description: "Namespace"
    required: true
runs:
  using: "node12"
  main: "dist/index.js"